# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 23:05
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('updated_ts', models.DateTimeField(auto_now=True)),
                ('slug', models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('updated_ts', models.DateTimeField(auto_now=True)),
                ('slug', models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('plot', models.TextField(blank=True)),
                ('release_date', models.DateTimeField(blank=True)),
                ('rating', models.FloatField(default=0)),
                ('rank', models.FloatField(blank=True, null=True)),
                ('year', models.FloatField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('running_time_secs', models.FloatField(blank=True, null=True)),
                ('actors', models.ManyToManyField(related_name='actors', to='artists.Artist')),
                ('directors', models.ManyToManyField(related_name='directors', to='artists.Artist')),
                ('genres', models.ManyToManyField(to='movies.Genre')),
            ],
            options={
                'ordering': ('-year',),
            },
        ),
    ]
